services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: prj-ulo-cobranca
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - ulo-network

  db:
    image: postgres:15-alpine
    container_name: ulo-db-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: 'bd-ulo-cobranca'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin123'
    volumes:
      - db-data-pg:/var/lib/postgresql/data
    networks:
      - ulo-network

networks:
  ulo-network:
    driver: bridge

volumes:
  db-data-pg:
